service: yrtt-tasks-backend-csharp-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: dotnetcore3.1
  lambdaHashingVersion: 20201221

  region: eu-west-2

package:
  individually: true

functions:
  getTasks-api:
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::getTasks

    package:
      artifact: bin/Release/netcoreapp3.1/tasks-api.zip
 
    events:
     - httpApi:
         path: /users/{userId}/tasks
         method: get

  saveTasks-api:
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::saveTasks

    package:
      artifact: bin/Release/netcoreapp3.1/tasks-api.zip
 
    events:
     - httpApi:
         path: /users/{userId}/tasks
         method: post
